/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  aux_sym_command_body_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_EQ = 4,
  anon_sym_DOT = 5,
  sym_comment = 6,
  aux_sym__cmd_token1 = 7,
  sym_identifier = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_string_token1 = 10,
  anon_sym_BSLASH = 11,
  aux_sym_string_token2 = 12,
  sym_reference = 13,
  sym_source_file = 14,
  sym__definition = 15,
  sym_command_definition = 16,
  sym_command_name = 17,
  sym_command_body = 18,
  sym__inline_command_body = 19,
  sym__overline_command_body = 20,
  sym_section_definition = 21,
  sym_section_name = 22,
  sym_variable_definition = 23,
  sym_variable_name = 24,
  sym_variable_value = 25,
  sym_command = 26,
  aux_sym__cmd = 27,
  sym_string = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym__overline_command_body_repeat1 = 30,
  aux_sym_string_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [aux_sym_command_body_token1] = "command_body_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [sym_comment] = "comment",
  [aux_sym__cmd_token1] = "_cmd_token1",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [sym_reference] = "reference",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_command_definition] = "command_definition",
  [sym_command_name] = "command_name",
  [sym_command_body] = "command_body",
  [sym__inline_command_body] = "_inline_command_body",
  [sym__overline_command_body] = "_overline_command_body",
  [sym_section_definition] = "section_definition",
  [sym_section_name] = "section_name",
  [sym_variable_definition] = "variable_definition",
  [sym_variable_name] = "variable_name",
  [sym_variable_value] = "variable_value",
  [sym_command] = "command",
  [aux_sym__cmd] = "_cmd",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__overline_command_body_repeat1] = "_overline_command_body_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_command_body_token1] = aux_sym_command_body_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_comment] = sym_comment,
  [aux_sym__cmd_token1] = aux_sym__cmd_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_reference] = sym_reference,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_command_definition] = sym_command_definition,
  [sym_command_name] = sym_command_name,
  [sym_command_body] = sym_command_body,
  [sym__inline_command_body] = sym__inline_command_body,
  [sym__overline_command_body] = sym__overline_command_body,
  [sym_section_definition] = sym_section_definition,
  [sym_section_name] = sym_section_name,
  [sym_variable_definition] = sym_variable_definition,
  [sym_variable_name] = sym_variable_name,
  [sym_variable_value] = sym_variable_value,
  [sym_command] = sym_command,
  [aux_sym__cmd] = aux_sym__cmd,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__overline_command_body_repeat1] = aux_sym__overline_command_body_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_body_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__cmd_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_command_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [sym_command_body] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym__overline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_name] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__cmd] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__overline_command_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\n', 8,
        '\r', 1,
        '"', 16,
        '#', 13,
        '.', 11,
        ':', 7,
        ';', 9,
        '=', 10,
        '@', 23,
        '\\', 20,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 8,
        '\r', 1,
        '"', 16,
        '#', 13,
        '.', 11,
        ':', 7,
        ';', 9,
        '=', 10,
        '@', 23,
        '\\', 20,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '@') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(18);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_command_body_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__cmd_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(14);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\r') ADVANCE(18);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_reference);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym__definition] = STATE(2),
    [sym_command_definition] = STATE(2),
    [sym_command_name] = STATE(24),
    [sym_section_definition] = STATE(2),
    [sym_variable_definition] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(3), 5,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      sym_variable_definition,
      aux_sym_source_file_repeat1,
  [27] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(20), 1,
      anon_sym_DOT,
    ACTIONS(23), 1,
      sym_identifier,
    STATE(24), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(3), 5,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      sym_variable_definition,
      aux_sym_source_file_repeat1,
  [54] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      aux_sym_command_body_token1,
    ACTIONS(28), 1,
      anon_sym_SEMI,
    ACTIONS(30), 1,
      aux_sym__cmd_token1,
    ACTIONS(32), 1,
      sym_reference,
    STATE(13), 1,
      sym_command_body,
    STATE(16), 1,
      aux_sym__cmd,
    STATE(19), 1,
      aux_sym__overline_command_body_repeat1,
    STATE(30), 1,
      sym_command,
    STATE(39), 2,
      sym__inline_command_body,
      sym__overline_command_body,
  [86] = 6,
    ACTIONS(34), 1,
      aux_sym__cmd_token1,
    ACTIONS(36), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      aux_sym__cmd,
    STATE(32), 1,
      sym_variable_value,
    STATE(36), 1,
      sym_string,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [106] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_DOT,
      sym_identifier,
  [117] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(40), 4,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_DOT,
      sym_identifier,
  [128] = 5,
    ACTIONS(44), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      aux_sym_string_token1,
    ACTIONS(48), 1,
      anon_sym_BSLASH,
    STATE(9), 1,
      aux_sym_string_repeat1,
    ACTIONS(42), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [145] = 5,
    ACTIONS(48), 1,
      anon_sym_BSLASH,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      aux_sym_string_token1,
    STATE(10), 1,
      aux_sym_string_repeat1,
    ACTIONS(42), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [162] = 5,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      aux_sym_string_token1,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(10), 1,
      aux_sym_string_repeat1,
    ACTIONS(42), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [179] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(62), 4,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_DOT,
      sym_identifier,
  [190] = 5,
    ACTIONS(30), 1,
      aux_sym__cmd_token1,
    ACTIONS(32), 1,
      sym_reference,
    STATE(16), 1,
      aux_sym__cmd,
    STATE(28), 1,
      sym_command,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [207] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_DOT,
      sym_identifier,
  [218] = 5,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      sym_string,
    STATE(35), 1,
      sym_section_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [235] = 2,
    ACTIONS(42), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(54), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [245] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__cmd_token1,
    STATE(18), 1,
      aux_sym__cmd,
    ACTIONS(70), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [259] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__cmd_token1,
    STATE(18), 1,
      aux_sym__cmd,
    ACTIONS(74), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [273] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      aux_sym__cmd_token1,
    STATE(18), 1,
      aux_sym__cmd,
    ACTIONS(76), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [287] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      aux_sym_command_body_token1,
    ACTIONS(81), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      aux_sym__overline_command_body_repeat1,
  [300] = 3,
    ACTIONS(83), 1,
      aux_sym__cmd_token1,
    STATE(17), 1,
      aux_sym__cmd,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [311] = 3,
    ACTIONS(85), 1,
      sym_identifier,
    STATE(27), 1,
      sym_variable_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__cmd_token1,
    ACTIONS(87), 1,
      aux_sym_command_body_token1,
    STATE(18), 1,
      aux_sym__cmd,
  [335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      aux_sym_command_body_token1,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    STATE(23), 1,
      aux_sym__overline_command_body_repeat1,
  [348] = 2,
    ACTIONS(94), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [356] = 2,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [364] = 2,
    ACTIONS(98), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [372] = 2,
    ACTIONS(100), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [380] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [388] = 2,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_command_body_token1,
    ACTIONS(106), 1,
      anon_sym_SEMI,
  [406] = 2,
    ACTIONS(108), 1,
      aux_sym_string_token2,
    ACTIONS(42), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_command_body_token1,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      aux_sym_command_body_token1,
  [428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_command_body_token1,
  [435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      aux_sym_command_body_token1,
  [442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_command_body_token1,
  [449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      aux_sym_command_body_token1,
  [456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      aux_sym_command_body_token1,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      aux_sym_command_body_token1,
  [470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      aux_sym_command_body_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 128,
  [SMALL_STATE(9)] = 145,
  [SMALL_STATE(10)] = 162,
  [SMALL_STATE(11)] = 179,
  [SMALL_STATE(12)] = 190,
  [SMALL_STATE(13)] = 207,
  [SMALL_STATE(14)] = 218,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 245,
  [SMALL_STATE(17)] = 259,
  [SMALL_STATE(18)] = 273,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 311,
  [SMALL_STATE(22)] = 322,
  [SMALL_STATE(23)] = 335,
  [SMALL_STATE(24)] = 348,
  [SMALL_STATE(25)] = 356,
  [SMALL_STATE(26)] = 364,
  [SMALL_STATE(27)] = 372,
  [SMALL_STATE(28)] = 380,
  [SMALL_STATE(29)] = 388,
  [SMALL_STATE(30)] = 396,
  [SMALL_STATE(31)] = 406,
  [SMALL_STATE(32)] = 414,
  [SMALL_STATE(33)] = 421,
  [SMALL_STATE(34)] = 428,
  [SMALL_STATE(35)] = 435,
  [SMALL_STATE(36)] = 442,
  [SMALL_STATE(37)] = 449,
  [SMALL_STATE(38)] = 456,
  [SMALL_STATE(39)] = 463,
  [SMALL_STATE(40)] = 470,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_body, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 5, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_definition, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__cmd, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd, 2, 0, 0), SHIFT_REPEAT(18),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_value, 1, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [96] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_name, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_name, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__overline_command_body, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
