/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  aux_sym_command_body_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_EQ = 4,
  sym_comment = 5,
  aux_sym__cmd_token1 = 6,
  sym_identifier = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_string_token1 = 9,
  anon_sym_BSLASH = 10,
  aux_sym_string_token2 = 11,
  sym_reference = 12,
  sym_source_file = 13,
  sym__definition = 14,
  sym_command_definition = 15,
  sym_command_name = 16,
  sym_command_body = 17,
  sym__inline_command_body = 18,
  sym__overline_command_body = 19,
  sym_section_definition = 20,
  sym_section_name = 21,
  sym_command = 22,
  aux_sym__cmd = 23,
  sym_string = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym__overline_command_body_repeat1 = 26,
  aux_sym_string_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [aux_sym_command_body_token1] = "command_body_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [aux_sym__cmd_token1] = "_cmd_token1",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [sym_reference] = "reference",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_command_definition] = "command_definition",
  [sym_command_name] = "command_name",
  [sym_command_body] = "command_body",
  [sym__inline_command_body] = "_inline_command_body",
  [sym__overline_command_body] = "_overline_command_body",
  [sym_section_definition] = "section_definition",
  [sym_section_name] = "section_name",
  [sym_command] = "command",
  [aux_sym__cmd] = "_cmd",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__overline_command_body_repeat1] = "_overline_command_body_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_command_body_token1] = aux_sym_command_body_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [aux_sym__cmd_token1] = aux_sym__cmd_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_reference] = sym_reference,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_command_definition] = sym_command_definition,
  [sym_command_name] = sym_command_name,
  [sym_command_body] = sym_command_body,
  [sym__inline_command_body] = sym__inline_command_body,
  [sym__overline_command_body] = sym__overline_command_body,
  [sym_section_definition] = sym_section_definition,
  [sym_section_name] = sym_section_name,
  [sym_command] = sym_command,
  [aux_sym__cmd] = aux_sym__cmd,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__overline_command_body_repeat1] = aux_sym__overline_command_body_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_body_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__cmd_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_command_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [sym_command_body] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym__overline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__cmd] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__overline_command_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 7,
        '\r', 1,
        '"', 14,
        '#', 11,
        ':', 6,
        ';', 8,
        '=', 9,
        '@', 20,
        '\\', 17,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 7,
        '\r', 1,
        '"', 14,
        '#', 11,
        ':', 6,
        ';', 8,
        '=', 9,
        '@', 20,
        '\\', 17,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '@') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_command_body_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__cmd_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_reference);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_reference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym__definition] = STATE(3),
    [sym_command_definition] = STATE(3),
    [sym_command_name] = STATE(20),
    [sym_section_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      aux_sym_command_body_token1,
    ACTIONS(13), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      aux_sym__cmd_token1,
    ACTIONS(17), 1,
      sym_reference,
    STATE(10), 1,
      sym_command_body,
    STATE(13), 1,
      aux_sym__cmd,
    STATE(18), 1,
      aux_sym__overline_command_body_repeat1,
    STATE(25), 1,
      sym_command,
    STATE(29), 2,
      sym__inline_command_body,
      sym__overline_command_body,
  [32] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(4), 4,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      aux_sym_source_file_repeat1,
  [55] = 6,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(26), 1,
      sym_identifier,
    STATE(20), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(4), 4,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      aux_sym_source_file_repeat1,
  [78] = 5,
    ACTIONS(15), 1,
      aux_sym__cmd_token1,
    ACTIONS(17), 1,
      sym_reference,
    STATE(13), 1,
      aux_sym__cmd,
    STATE(24), 1,
      sym_command,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [95] = 5,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    STATE(26), 1,
      sym_section_name,
    STATE(28), 1,
      sym_string,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [112] = 5,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(37), 1,
      aux_sym_string_token1,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    STATE(9), 1,
      aux_sym_string_repeat1,
    ACTIONS(33), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [129] = 5,
    ACTIONS(39), 1,
      anon_sym_BSLASH,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      aux_sym_string_token1,
    STATE(7), 1,
      aux_sym_string_repeat1,
    ACTIONS(33), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [146] = 5,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(47), 1,
      aux_sym_string_token1,
    ACTIONS(50), 1,
      anon_sym_BSLASH,
    STATE(9), 1,
      aux_sym_string_repeat1,
    ACTIONS(33), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [163] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [173] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [183] = 2,
    ACTIONS(33), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(45), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      aux_sym__cmd_token1,
    STATE(16), 1,
      aux_sym__cmd,
    ACTIONS(57), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [207] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      aux_sym__cmd_token1,
    STATE(16), 1,
      aux_sym__cmd,
    ACTIONS(61), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [221] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [231] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      aux_sym__cmd_token1,
    STATE(16), 1,
      aux_sym__cmd,
    ACTIONS(65), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [245] = 3,
    ACTIONS(70), 1,
      aux_sym__cmd_token1,
    STATE(14), 1,
      aux_sym__cmd,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      aux_sym_command_body_token1,
    ACTIONS(72), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      aux_sym__overline_command_body_repeat1,
  [269] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      aux_sym_command_body_token1,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      aux_sym__overline_command_body_repeat1,
  [282] = 2,
    ACTIONS(79), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [290] = 2,
    ACTIONS(81), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [298] = 2,
    ACTIONS(83), 1,
      aux_sym_string_token2,
    ACTIONS(33), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [306] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_command_body_token1,
    ACTIONS(89), 1,
      anon_sym_SEMI,
  [332] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      aux_sym_command_body_token1,
  [339] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_command_body_token1,
  [346] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      aux_sym_command_body_token1,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_command_body_token1,
  [360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      aux_sym_command_body_token1,
  [367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_command_body_token1,
  [374] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      aux_sym_command_body_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 55,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 95,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 163,
  [SMALL_STATE(11)] = 173,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 193,
  [SMALL_STATE(14)] = 207,
  [SMALL_STATE(15)] = 221,
  [SMALL_STATE(16)] = 231,
  [SMALL_STATE(17)] = 245,
  [SMALL_STATE(18)] = 256,
  [SMALL_STATE(19)] = 269,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 298,
  [SMALL_STATE(23)] = 306,
  [SMALL_STATE(24)] = 314,
  [SMALL_STATE(25)] = 322,
  [SMALL_STATE(26)] = 332,
  [SMALL_STATE(27)] = 339,
  [SMALL_STATE(28)] = 346,
  [SMALL_STATE(29)] = 353,
  [SMALL_STATE(30)] = 360,
  [SMALL_STATE(31)] = 367,
  [SMALL_STATE(32)] = 374,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_definition, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_body, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__cmd, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__cmd, 2, 0, 0), SHIFT_REPEAT(16),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_name, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__overline_command_body, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
