/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  aux_sym_command_body_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_EQ = 4,
  sym_comment = 5,
  aux_sym_cmd_token1 = 6,
  sym_identifier = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_string_token1 = 9,
  anon_sym_BSLASH = 10,
  aux_sym_string_token2 = 11,
  sym_source_file = 12,
  sym__definition = 13,
  sym_command_definition = 14,
  sym_command_name = 15,
  sym_command_body = 16,
  sym__inline_command_body = 17,
  sym__overline_command_body = 18,
  sym_section_definition = 19,
  sym_section_name = 20,
  sym_cmd = 21,
  sym_string = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym__overline_command_body_repeat1 = 24,
  aux_sym_cmd_repeat1 = 25,
  aux_sym_string_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [aux_sym_command_body_token1] = "command_body_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [aux_sym_cmd_token1] = "cmd_token1",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_command_definition] = "command_definition",
  [sym_command_name] = "command_name",
  [sym_command_body] = "command_body",
  [sym__inline_command_body] = "_inline_command_body",
  [sym__overline_command_body] = "_overline_command_body",
  [sym_section_definition] = "section_definition",
  [sym_section_name] = "section_name",
  [sym_cmd] = "cmd",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__overline_command_body_repeat1] = "_overline_command_body_repeat1",
  [aux_sym_cmd_repeat1] = "cmd_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_command_body_token1] = aux_sym_command_body_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [aux_sym_cmd_token1] = aux_sym_cmd_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_command_definition] = sym_command_definition,
  [sym_command_name] = sym_command_name,
  [sym_command_body] = sym_command_body,
  [sym__inline_command_body] = sym__inline_command_body,
  [sym__overline_command_body] = sym__overline_command_body,
  [sym_section_definition] = sym_section_definition,
  [sym_section_name] = sym_section_name,
  [sym_cmd] = sym_cmd,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__overline_command_body_repeat1] = aux_sym__overline_command_body_repeat1,
  [aux_sym_cmd_repeat1] = aux_sym_cmd_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_body_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_cmd_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_command_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [sym_command_body] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym__overline_command_body] = {
    .visible = false,
    .named = true,
  },
  [sym_section_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__overline_command_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cmd_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 7,
        '\r', 1,
        '"', 14,
        '#', 11,
        ':', 6,
        ';', 8,
        '=', 9,
        '\\', 17,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 7,
        '\r', 1,
        '"', 14,
        '#', 11,
        ':', 6,
        ';', 8,
        '=', 9,
        '\\', 17,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_command_body_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_cmd_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym__definition] = STATE(3),
    [sym_command_definition] = STATE(3),
    [sym_command_name] = STATE(19),
    [sym_section_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_command_body_token1] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_EQ,
    ACTIONS(16), 1,
      sym_identifier,
    STATE(19), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(2), 4,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      aux_sym_source_file_repeat1,
  [23] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_command_name,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    STATE(2), 4,
      sym__definition,
      sym_command_definition,
      sym_section_definition,
      aux_sym_source_file_repeat1,
  [46] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_command_body_token1,
    ACTIONS(23), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      aux_sym_cmd_token1,
    STATE(12), 1,
      aux_sym_cmd_repeat1,
    STATE(14), 1,
      sym_command_body,
    STATE(16), 1,
      aux_sym__overline_command_body_repeat1,
    STATE(23), 1,
      sym_cmd,
    STATE(27), 2,
      sym__inline_command_body,
      sym__overline_command_body,
  [75] = 5,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_section_name,
    STATE(25), 1,
      sym_string,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [92] = 5,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      aux_sym_string_token1,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    STATE(7), 1,
      aux_sym_string_repeat1,
    ACTIONS(31), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [109] = 5,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      aux_sym_string_token1,
    STATE(8), 1,
      aux_sym_string_repeat1,
    ACTIONS(31), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [126] = 5,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      aux_sym_string_token1,
    ACTIONS(48), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      aux_sym_string_repeat1,
    ACTIONS(31), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [143] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [153] = 4,
    ACTIONS(25), 1,
      aux_sym_cmd_token1,
    STATE(12), 1,
      aux_sym_cmd_repeat1,
    STATE(22), 1,
      sym_cmd,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [167] = 2,
    ACTIONS(31), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(43), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [177] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      aux_sym_cmd_token1,
    STATE(15), 1,
      aux_sym_cmd_repeat1,
    ACTIONS(53), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [191] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [201] = 2,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      anon_sym_EQ,
      sym_identifier,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      aux_sym_cmd_token1,
    STATE(15), 1,
      aux_sym_cmd_repeat1,
    ACTIONS(61), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [225] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      aux_sym_command_body_token1,
    ACTIONS(66), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      aux_sym__overline_command_body_repeat1,
  [238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      aux_sym_command_body_token1,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      aux_sym__overline_command_body_repeat1,
  [251] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [259] = 2,
    ACTIONS(75), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [267] = 2,
    ACTIONS(77), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [275] = 2,
    ACTIONS(79), 1,
      aux_sym_string_token2,
    ACTIONS(31), 2,
      aux_sym_command_body_token1,
      sym_comment,
  [283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      aux_sym_command_body_token1,
      anon_sym_SEMI,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      aux_sym_command_body_token1,
    ACTIONS(83), 1,
      anon_sym_SEMI,
  [301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym_command_body_token1,
  [308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      aux_sym_command_body_token1,
  [315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      aux_sym_command_body_token1,
  [322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      aux_sym_command_body_token1,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_command_body_token1,
  [336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      aux_sym_command_body_token1,
  [343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_command_body_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 109,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 143,
  [SMALL_STATE(10)] = 153,
  [SMALL_STATE(11)] = 167,
  [SMALL_STATE(12)] = 177,
  [SMALL_STATE(13)] = 191,
  [SMALL_STATE(14)] = 201,
  [SMALL_STATE(15)] = 211,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 238,
  [SMALL_STATE(18)] = 251,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 267,
  [SMALL_STATE(21)] = 275,
  [SMALL_STATE(22)] = 283,
  [SMALL_STATE(23)] = 291,
  [SMALL_STATE(24)] = 301,
  [SMALL_STATE(25)] = 308,
  [SMALL_STATE(26)] = 315,
  [SMALL_STATE(27)] = 322,
  [SMALL_STATE(28)] = 329,
  [SMALL_STATE(29)] = 336,
  [SMALL_STATE(30)] = 343,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_definition, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_body, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_definition, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cmd_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cmd_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__overline_command_body_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_name, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_command_body, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__overline_command_body, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
